* проверить
** DONE подключение плагинов, можно ли сделать дропдану
   Подключение сторонних плагинов работает.
*** Странное поведение react-select
    Версии реакта/селекта?
** TODO выполнение ajax запросов
   Можно ли, и как просто выполнять запросы на сервер
*** react-flux-servant
*** TODO завести простейший сервер
*** TODO завести API
*** TODO сделать докер для локальной отладки
    Чтобы отдавать статику завести локальный nginx с конфигом и статикой из
    todoClient плюс контейнер с todoServer
*** TODO выполнить запрос на создание с помощью xhr
*** TODO выполнить запрос на просмотр с помощью react-flux-servant
** TODO Вызов коллбека с параметром коллбеком
   У react-select есть параметр "loadOptions" который принимает функцию, которая
   принимает функцию в качестве параметра.
* странности и подводные камни
** react-flux
*** параметры коллбеков
    Странные неявные преобразования типов. Наткнулся: хаскельная функция ожидает
    строку, коллбэк был вызван с объектом в качестве параметра, функция
    была вызвана с пустой строкой в качестве параметра (в консоли ошибк нет).
* винрар
** aeson инстансы
   Можно использовать aeson для инстансов FromJSVal/ToJSVal
** можно делать биндинги к плагинам
   Вполне подъемная задача тайпсейфных биндингов в внешним компонентам на реакте.
